server:
  port: 8001
#mybatis配置
mybatis:
  type-aliases-package: com.heizi.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


#spring配置
spring:
  application:
    name: springcloud.provider.dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #org.gjt.mysql.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
#Eureka配置 服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/，http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001 #修改Eureka上的默认描述信息

#Info配置
info:
  app.name: heizi-springcloud
  company.name: blog.heiziStudy.com


